/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201907221221.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COMMONAPI_Ipc_DBUS_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_Ipc_DBUS_STUB_ADAPTER_HPP_

#include <v1/commonapi/IpcStub.hpp>
#include "v1/commonapi/IpcDBusDeployment.hpp"
#include <v1/commonapi/IpcDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace commonapi {

template <typename _Stub = ::v1::commonapi::IpcStub, typename... _Stubs>
class IpcDBusStubAdapterInternal
    : public virtual IpcStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> IpcDBusStubAdapterHelper;

    ~IpcDBusStubAdapterInternal() {
        deactivateManagedInstances();
        IpcDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return Ipc::getInterface();
    }

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::commonapi::IpcStub,
        CommonAPI::Version
        > getIpcInterfaceVersionStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::commonapi::IpcStub,
        std::tuple< Ipc::IpcStruct>,
        std::tuple< int32_t>,
        std::tuple< ::v1::commonapi::Ipc_::IpcStructDeployment_t>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > structInMethodStubDispatcher;

    IpcDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      IpcDBusStubAdapterHelper(_address, _connection, false, _stub) {
        IpcDBusStubAdapterHelper::addStubDispatcher({ "structInMethod", "(iiiii)" }, &structInMethodStubDispatcher);
        IpcDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getIpcInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"structInMethod\">\n"
            "<arg name=\"_structParameter\" type=\"(iiiii)\" direction=\"in\" />\n"
            "<arg name=\"_output\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::commonapi::IpcStub,
    CommonAPI::Version
    > IpcDBusStubAdapterInternal<_Stub, _Stubs...>::getIpcInterfaceVersionStubDispatcher(&IpcStub::lockInterfaceVersionAttribute, &IpcStub::getInterfaceVersion, "uu");


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::commonapi::IpcStub,
    std::tuple< Ipc::IpcStruct>,
    std::tuple< int32_t>,
    std::tuple< ::v1::commonapi::Ipc_::IpcStructDeployment_t>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>

    > IpcDBusStubAdapterInternal<_Stub, _Stubs...>::structInMethodStubDispatcher(
    &IpcStub::structInMethod, "i",
    std::make_tuple(static_cast< ::v1::commonapi::Ipc_::IpcStructDeployment_t* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)));


template <typename _Stub = ::v1::commonapi::IpcStub, typename... _Stubs>
class IpcDBusStubAdapter
    : public IpcDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< IpcDBusStubAdapter<_Stub, _Stubs...>> {
public:
    IpcDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          IpcDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_Ipc_DBUS_STUB_ADAPTER_HPP_
