/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.12.v201907221047.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#include <v1/commonapi/IpcStubDefault.hpp>
#include <assert.h>

namespace v1 {
namespace commonapi {

IpcStubDefault::IpcStubDefault():
        remoteEventHandler_(this),
        interfaceVersion_(Ipc::getInterfaceVersion()) {
}

const CommonAPI::Version& IpcStubDefault::getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
    (void)_client;
    return interfaceVersion_;
}

IpcStubRemoteEvent* IpcStubDefault::initStubAdapter(const std::shared_ptr< IpcStubAdapter> &_adapter) {
    CommonAPI::Stub<IpcStubAdapter, IpcStubRemoteEvent>::stubAdapter_ = _adapter;
    return &remoteEventHandler_;
}


void IpcStubDefault::structInMethod(const std::shared_ptr<CommonAPI::ClientId> _client, Ipc::IpcStruct _structParameter, structInMethodReply_t _reply) {
    (void)_client;
    (void)_structParameter;
    int32_t output = 0;
    _reply(output);
}




IpcStubDefault::RemoteEventHandler::RemoteEventHandler(IpcStubDefault *_defaultStub)
    : 
      defaultStub_(_defaultStub) {
}

} // namespace commonapi
} // namespace v1
